---
title: "Just some fun"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width = 8, fig.height = 5)
library(tidyverse)
library(tidymodels)
```

Going to be playing with the standard iris data

```{r}

data(iris)
glimpse(iris)
```


## Explore data


```{r}
iris %>%
  ggplot(aes(Sepal.Length, Petal.Length, color = Species)) +
  geom_point(alpha = 0.5) +
  theme_bw()
```


## Build models

```{r}
set.seed(123)
iris_split <- initial_split(iris, strata = Species)
iris_train <- training(iris_split)
iris_test <- testing(iris_split)

set.seed(234)
iris_folds <- vfold_cv(iris_train, strata = Species)
iris_folds
```

# Multinomial regression versus random forest

```{r}
lr_mod <- 
  multinom_reg(penalty = tune(), mixture = 1) %>% 
  set_engine("glmnet")


lr_recipe <- 
  recipe(Species ~ ., data = iris_train) %>% 
  step_zv(all_predictors()) %>% 
  step_normalize(all_predictors())

lr_workflow <- 
  workflow() %>% 
  add_model(lr_mod) %>% 
  add_recipe(lr_recipe)

lr_reg_grid <- tibble(penalty = 10^seq(-4, -1, length.out = 30))

lr_res <- 
  lr_workflow %>% 
  tune_grid(iris_folds,
            grid = lr_reg_grid,
            control = control_grid(save_pred = TRUE),
            metrics = metric_set(roc_auc))

  lr_res %>% 
    show_best(metric = "roc_auc")
```

```{r}

cores <- parallel::detectCores()
rf_mod <- 
  rand_forest(mtry = tune(), min_n = tune(), trees = 1000) %>% 
  set_engine("ranger", num.threads = cores) %>% 
  set_mode("classification")

rf_recipe <- 
  recipe(Species ~ ., data = iris_train)

rf_workflow <- 
  workflow() %>% 
  add_model(rf_mod) %>% 
  add_recipe(rf_recipe)

set.seed(345)
rf_res <- 
  rf_workflow %>% 
  tune_grid(iris_folds,
            grid = 25,
            control = control_grid(save_pred = TRUE),
            metrics = metric_set(roc_auc))

rf_res %>% 
  show_best(metric = "roc_auc")
```


## Evaluate models

```{r}

lr_best <- lr_res %>%
  select_best(metric = "roc_auc")

rf_best <- rf_res %>%
  select_best(metric = "roc_auc")
```

## Fit Final Model

```{r}
final_wf <- 
  lr_workflow %>% 
  finalize_workflow(lr_best)


final_fit <- 
  final_wf %>%
  last_fit(iris_split) 

final_fit %>%
  collect_metrics()

final_fit %>%
  collect_predictions() %>%
  conf_mat(Species, .pred_class)
```

